# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10, verbose_name='State')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('set_alert', models.PositiveSmallIntegerField(blank=True, default=0, help_text='This is used for alert message. If you want to trigger alert before due date then only set this.', null=True)),
                ('sub_task', models.ForeignKey(blank=True, help_text='This is for sub task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_date',),
            },
        ),
    ]
