# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sub_task',
        ),
        migrations.AddField(
            model_name='task',
            name='sub_task',
            field=models.ManyToManyField(blank=True, help_text='This is for sub task', null=True, related_name='_task_sub_task_+', to='core.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], default='parent', help_text='This is used to differentiate if the task is sub-task then it will be changed child.', max_length=11, verbose_name='Task Type'),
        ),
    ]
