# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20181114_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('user', 'title')]),
        ),
    ]
